### ISSUE TITLE
How to update manifest in concourse?

### ISSUE THREAD

**Issue by jaderiverstokes** [pivotal-cf/email-resource#1]
Hi,

I could not find a manifest file on vagrant box. Could you please let us know the path of the manifest file to update the concourse manifest to add email as a resource-type?

Thanks.

**Comment by rosenhouse** [comment]
The README in this repo is out of date.  The recommended way to use a custom resource is now the `resource_types` feature in Concourse: http://concourse.ci/configuring-resource-types.html

**Comment by jaderiverstokes** [comment]
Thanks!
