### ISSUE TITLE
v1.0.5 now fails job when message body is empty

### ISSUE THREAD

**Issue by idoru** [pivotal-cf/email-resource#14]
Hi,
our pipeline is using email-resource and we are observing some breaking behavior since the latest release. 

When e-mail body is empty, our job now unexpectedly fails (with the error "Message not sent because the message body is empty and send_empty_body parameter was set to false. Github readme: https://github.com/pivotal-cf/email-resource").

Seems this error output used to simply be emitted, but now bubbles up and triggers the fail in this change:
https://github.com/pivotal-cf/email-resource/commit/393b32abf6193d0fa41a6b570122c827e70bcd11#diff-095c0632d71d85e648abdfd1442cb59fR143

However, we don't want to set "send_empty_body" to true, as receiving empty e-mails would not only be useless but annoying; the behavior we have been relying on is that no e-mail is sent, and the job should not fail.

**Comment by calebwashburn** [comment]
Fixed with latest build.
