### ISSUE TITLE
AWS SES smtp timeout

### ISSUE THREAD

**Issue by dmasilamani** [pivotal-cf/email-resource#21]
I get the following when I try to send email using AWS SES

> dial tcp: lookup <aws smtp> on <docker worker ip address>:53: read udp 10.254.0.66:50036-><docker worker ip address>:53: i/o timeout

I have concourse running as docker. I am able to send email from concourse server and concourse worker as well but when triggered through job failure I am getting the above error.\

Any clue on this?

![email-error](https://user-images.githubusercontent.com/21095805/35667746-cf67949e-0754-11e8-91ec-f827f779c703.PNG)

**Comment by mujahidsof** [comment]
Hi,
I am also receiving same error  :(

**Comment by calebwashburn** [comment]
This looks like an issue with your concourse DNS setup.  Port 53 is for looking up DNS records.  What port do you have configured in your resource as AWS uses the following: 25, 465 or 587

**Comment by mujahidsof** [comment]
@calebwashburn  
I have used all ports with no luck, concourse was hosted locally in my PC.
Then i spin-up concourse in AWS ran again worked fine.

Thanks
Mujahid Alikhan Khasigi

**Comment by calebwashburn** [comment]
Ok... So appears network issues on your setup not the resource itself.
