### ISSUE TITLE
attaching files

### ISSUE THREAD

**Issue by shreddedbacon** [pivotal-cf/email-resource#22]
How can I use this resource to add attachments generated in a task to an email?

**Comment by calebwashburn** [comment]
This resource currently doesn't support adding attachments.  Would need to add this feature

**Comment by labrown** [comment]
Having attachments would be very useful.

There is a concourse email resource out there that does support attachments.
https://github.com/mdomke/concourse-email-resource
Might contact him and see if he'd contribute code.

**Comment by calebwashburn** [comment]
@shreddedbacon @labrown Added support for attachment with latest (1.0.15).  See sample pipeline for usage as this supports attaching any file that matches globs you provide.

https://github.com/pivotal-cf/email-resource/blob/master/example/demo-pipeline-attachments.yml

**Comment by labrown** [comment]
Awesome!  Thanks much
