### ISSUE TITLE
Smtp client should use domain from sender address instead of localhost

### ISSUE THREAD

**Issue by tchaloupka** [pivotal-cf/email-resource#27]
We use `smtp-relay.gmail.com` as a SMTP and until recently all works great.
But now email task ends with: `v1.0.10-17dce345143614aa96d9a57c3f6ab8c5d6f3e664 - EOF`

Well obviously it doesn't say much.. :(

I wanted to figure out the reason so compiled the `out` and debugged it with gdb and by hand created json file with the correct parameters.

And I figured that the problem is with this:
```GO
if err = c.Hello("localhost"); err != nil {
	return "", err
}
```
This ends up with EOL error.

When I tried:
```
telnet smtp-relay.gmail.com 587

helo localhost
421 4.7.0 Try again later, closing connection. (EHLO) h4-v6sm68320wrq.12 - gsmtp
Connection closed by foreign host.
```
So it indeed fails for localhost but not for our domain.

In the smtp relay documentation (https://support.google.com/a/answer/2956491?hl=en) is this:

> We recommend that you configure your mail server to present a unique identifier (such as your domain name or the name of your mail server) in the HELO or EHLO command in the SMTP relay connections your server makes to Google. Avoid using generic names such as "localhost" or "smtp-relay.gmail.com," which can occasionally result in issues with DoS limits.

So I guess the better approach would be to use domain part from the sender address instead of `localhost`

**Comment by calebwashburn** [comment]
Made a fix and released.  please validate this is working.

**Comment by tchaloupka** [comment]
Thanks!
Well it works (for now), but as it uses the SMTP host now, I'm still not sure it's the correct approach.

From SMTP RFC (https://tools.ietf.org/html/rfc821#page-13)
> In the HELO command the host sending the command identifies itself; the command may be interpreted as saying "Hello, I am <domain>".

And also in above mentioned gmail docs:
> Avoid using generic names such as "localhost" or "smtp-relay.gmail.com," which can occasionally result in issues with DoS limits.

Which is exactly what is used after the change.

So from that I would say it should probably use the domain from the sender email address or make it an optional parameter?

**Comment by calebwashburn** [comment]
Good catch.  I have updated this resource to have an optional input of `host_origin` to allow setting this, if not set `localhost` will be used.  https://github.com/pivotal-cf/email-resource/releases/tag/v1.0.12
