### ISSUE TITLE
Getting EOF error - using example pipeline

### ISSUE THREAD

**Issue by bhutkovskyysos** [pivotal-cf/email-resource#31]
I was trying to setup email notifications using this resource and following the steps from readme but I am getting the following error:

v1.0.13-b83fdf4d8c967bce40e77019a19a0c451a59e3c6 - EOF

I also tried using demo-pipeline.yml from the examples and still got the same error. I cannot really debug this as I'm unable to intercept into this resource. Concourse version I am running is v3.14.1.  Any help is appreciated.

**Comment by calebwashburn** [comment]
@bhutkovskyysos Can you provide the entire error output?  Also any additional details about what SMTP service you are using and provide scrubbed configuration.

**Comment by bhutkovskyysos** [comment]
That was the entire error, nothing meaningful that would help debug this. It turned out I was using port 465, which was causing the error. I switched to 587 and everything worked.
