### ISSUE TITLE
send-email constructs errors out with EOF

### ISSUE THREAD

**Issue by saisantoshi76** [pivotal-cf/email-resource#32]
v1.0.14-53e61dda6f626d66267b4890c0653cc87f728881 - EOF

ranmanda-Mac:gated-pipelines ranmanda$ fly -t tutorial trigger-job -w -j shipit/send-email
started shipit/send-email #4

initializing
running sh -exc # ensure you esape the ${BUILD_ID} variable with leading \
echo -e "Email resource demo on $(date): build \${BUILD_ID}" > email-out/${OUTPUT_SUBJECT_FILE_NAME}
echo -e "Cheers!\n\n \
Build ID: \${BUILD_ID} \n \
Build Name: \${BUILD_NAME} \n \
Build Job Name: \${BUILD_JOB_NAME} \n \
Build Pipeline Name: \${BUILD_PIPELINE_NAME} \n \
ATC External URL: \${ATC_EXTERNAL_URL}" > email-out/${OUTPUT_BODY_FILE_NAME}

+ date
+ echo -e Email resource demo on Thu Feb 28 22:08:33 UTC 2019: build ${BUILD_ID}
+ echo -e Cheers!\n\n Build ID: ${BUILD_ID} \n Build Name: ${BUILD_NAME} \n Build Job Name: ${BUILD_JOB_NAME} \n Build Pipeline Name: ${BUILD_PIPELINE_NAME} \n ATC External URL: ${ATC_EXTERNAL_URL}
v1.0.14-53e61dda6f626d66267b4890c0653cc87f728881 - EOF
failed

**Comment by calebwashburn** [comment]
@saisantoshi76 can you provide your pipeline that creates this issue.  Mainly wanting to see configuration options on resource as well as on the usage within a job.

**Comment by saisantoshi76** [comment]
@calebwashburn -Thanks. Below is my pipeline code. It would be great if you can also let me know how do we debug these kind of issues. Any pointers on this is much appreciated.

---
resource_types:
  - name: email
    type: docker-image
    source:
      repository: pcfseceng/email-resource

resources:
- name: send-an-email
  type: email
  source:
    smtp:
      host: smtp.gmail.com
      port: "465"
      username: xxxxx@gmail.com
      password: xxxxx
    from: xxxxx@gmail.com
    to: [ xxxxx@gmail.com ]

jobs:
  - name: send-email
    plan:
      - task: prep-email
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: concourse/buildroot
              tag: git
          params:
            OUTPUT_SUBJECT_FILE_NAME: generated-subject
            OUTPUT_BODY_FILE_NAME: generated-body
          run:
            path: sh
            args:
            - -exc
            - |
              # ensure you esape the ${BUILD_ID} variable with leading \
              echo -e "Email resource demo on $(date): build \${BUILD_ID}" > email-out/${OUTPUT_SUBJECT_FILE_NAME}
              echo -e "Cheers!\n\n \
              Build ID: \${BUILD_ID} \n \
              Build Name: \${BUILD_NAME} \n \
              Build Job Name: \${BUILD_JOB_NAME} \n \
              Build Pipeline Name: \${BUILD_PIPELINE_NAME} \n \
              ATC External URL: \${ATC_EXTERNAL_URL}" > email-out/${OUTPUT_BODY_FILE_NAME}
          outputs:
          - name: email-out
      - put: send-an-email
        params:
          subject: generated-subject-file
          body: generated-body-file
          to: generated-to-file

**Comment by calebwashburn** [comment]
A few things.  Don't believe you are passing the output from prep task correctly and also there is never a `generated-to-file`  try the following

```
resource_types:
- name: email
  type: docker-image
  source:
    repository: pcfseceng/email-resource

resources:
- name: send-an-email
  type: email
  source:
    smtp:
      host: smtp.gmail.com
      port: "465"
      username: xxxxx@gmail.com
      password: xxxxx
      from: xxxxx@gmail.com
      to: [ xxxxx@gmail.com ]
jobs:
- name: send-email
  plan:
    - task: prep-email
      config:
        platform: linux
        image_resource:
        type: docker-image
        source:
          repository: concourse/buildroot
          tag: git
        run:
          path: sh
          args:
            - -exc
            - |
            # ensure you esape the ${BUILD_ID} variable with leading 
            echo -e "Email resource demo on $(date): build ${BUILD_ID}" > email-out/generated-subject-file
            echo -e "Cheers!\n\n 
            Build ID: ${BUILD_ID} \n 
            Build Name: ${BUILD_NAME} \n 
            Build Job Name: ${BUILD_JOB_NAME} \n 
            Build Pipeline Name: ${BUILD_PIPELINE_NAME} \n 
            ATC External URL: ${ATC_EXTERNAL_URL}" > email-out/generated-body-file
        outputs:
          name: email-out
    - put: send-an-email
      params:
        subject: email-out/generated-subject-file
        body: email-out/generated-body-file
```

**Comment by calebwashburn** [comment]
Using the examples directory will help as well - https://github.com/pivotal-cf/email-resource/blob/master/example/demo-pipeline-dynamic-recipients.yml

**Comment by saisantoshi76** [comment]
@calebwashburn - Thanks a lot. I tried your suggestion but still the same. I am inserting the complete pipeline code that I am using. Please let me know if there is anything missing from the below. The error message is not very helpful in debugging what is wrong. Is there any way we can debug to nail down the root issue. In my opinion, the logs should give more intutive message than the EOF. Even if there is any issue with the pipeline code, the error message should be very descriptive for the users to correct their code. Not having the debugging capability here makes it harder to nail down the issue.

`---
resource_types:
  - name: email
    type: docker-image
    source:
      repository: pcfseceng/email-resource
resources:
- name: send-an-email
  type: email
  source:
    smtp:
      host: smtp.gmail.com
      port: "465"
      username: xxxxxx@gmail.com
      password: xxxxxx
    from: xxxxxx@gmail.com
    to: [ xxxxxx@gmail.com ]
jobs:
- name: send-email
  plan:
    - task: prep-email
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: concourse/buildroot
            tag: git
        params:
            OUTPUT_SUBJECT_FILE_NAME: generated-subject
            OUTPUT_BODY_FILE_NAME: generated-body
        run:
          path: sh
          args:
          - -exc
          - |
            # ensure you esape the ${BUILD_ID} variable with leading
            echo -e "Email resource demo on $(date): build ${BUILD_ID}" > email-out/generated-subject-file
            echo -e "Cheers!\n\n
            Build ID: ${BUILD_ID} \n
            Build Name: ${BUILD_NAME} \n
            Build Job Name: ${BUILD_JOB_NAME} \n
            Build Pipeline Name: ${BUILD_PIPELINE_NAME} \n
            ATC External URL: ${ATC_EXTERNAL_URL}" > email-out/generated-body-file
        outputs:
        - name: email-out
    - put: send-an-email
      params:
        subject: email-out/generated-subject-file
        body: email-out/generated-body-file
`

**Comment by calebwashburn** [comment]
Closing this issue, feel free to re-open if you still have issues.
