### ISSUE TITLE
[Feature request] Simple way (by string) to describe email recipients in the out parameters

### ISSUE THREAD

**Issue by pjww** [pivotal-cf/email-resource#35]
Hi!

This resource is very useful in my projects, good work! 👏👏

However, one thing is quite uncomfortable: the lack of `to_text` field for the `out` parameters (that is an option to supply a string instead of file).

I mean, most of time I only need to mail _constant_ / _hardcoded_ recipients. In such case, I need to create a whole task at the beginning of the job just to prepare a file with comma-separated values (emails).

Also note that I can't define recipients under `resource` section, since in different jobs I want to mail different users.

I would be very glad if you added this feature. I really need that.

Cheers! ✋

**Comment by calebwashburn** [comment]
Published as version 1.0.18/latest

**Comment by pjww** [comment]
Thank you! Works like a charm! 👏👏
