### ISSUE TITLE
unmarshiling error

### ISSUE THREAD

**Issue by viva0007** [pivotal-cf/email-resource#49]
Concourse Version: 7.3.2

PUT email task fails with this error.

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/102993431/161614766-c3986b38-ac8a-4bec-9f66-de21603d9f0c.png">

Here is my pipeline.

<img width="1319" alt="image" src="https://user-images.githubusercontent.com/102993431/161614550-6b694435-5069-4e6b-9988-6cc68ad331d2.png">

**Comment by calebwashburn** [comment]
Need to specify an array of strings (even if just one) for the `to:` attribute.  ie ```to: [ "dev-team@example.com", "product@example.net" ]```

**Comment by viva0007** [comment]
Did the magic !
