### ISSUE TITLE
Unable to checkout bitbucket.org/chrj/smtpd

### ISSUE THREAD

**Issue by lyle-ascn** [pivotal-cf/email-resource#50]
It look like Christian Joergensen  has remove all his code from Bitbucket.org as I am receiving a Repository not found.

**Comment by calebwashburn** [comment]
Try again as moved to use go mod and vendored in dependencies.  Need to pull latest changes but should be able to compile now locally

**Comment by lyle-ascn** [comment]
Thank you for doing the update
