### ISSUE TITLE
SMTP username

### ISSUE THREAD

**Issue by fabianschwarzfritz** [pivotal-cf/email-resource#6]
Hi,

I'd like to integrate this email-resource on a development landscape. I do have access to an SMTP server there, but without user/password for authentication. I don't think I'd need username/password in a dedicated development landscape. 

Unfortunately with this plugin I have to provide username/password, and it does not works for my case. I'd be happy to see that feature. Or is that something that won't be supported as part of this resource?

Cheers,
Fabian

**Comment by mrmcmuffinz** [comment]
HI, any idea when this feature will go in? I see that #11 has a pull request already pending but no review or activity on it for a while.

**Comment by calebwashburn** [comment]
Fixed with latest release of this resource.  Now supports `anonymous: true/false` on source configuration.
