### ISSUE TITLE
SMTP headers compatibility with RFC 5322

### ISSUE THREAD

**Issue by tushar-dadlani** [pivotal-cf/email-resource#9]
> REASON550 5.7.1 [167.89.13.30 11] Our system has detected that this message is not RFC 5322 compliant: 'From' header is missing. To reduce the amount of spam sent to Gmail, this message has been blocked. Please visit https://support.google.com/mail/?p=RfcMessageNonCompliant and review RFC 5322 specifications for more information. REDACTED - gsmtp SMTP-ID<REDACTED>PROCESSED STRINGSeptember 14, 2016 - 02:13:36 REDACTED

We noticed that sending an email message using a traditional SMTP server causes the server to block the requests as the body doesn't contain the default `To` and `From` headers needed to be [RFC 5322](https://tools.ietf.org/html/rfc5322) compliant. 

From the godocs for smtp library
https://golang.org/pkg/net/smtp/#SendMail
`The msg parameter should be an RFC 822-style email with headers first, a blank line, and then the message body.`

**Comment by mmb** [comment]
Fixed by PR #10.
